"""Machine-readable API error codes."""

STALE_RESOLUTION_SESSION = "STALE_RESOLUTION_SESSION"
STALE_CLARIFICATION_SESSION = "STALE_CLARIFICATION_SESSION"
STALE_VARIANT_PREVIEW = "STALE_VARIANT_PREVIEW"
STALE_FEEDBACK_PREVIEW = "STALE_FEEDBACK_PREVIEW"
PROJECT_GRAPH_DRIFT = "PROJECT_GRAPH_DRIFT"
PACK_HASH_DRIFT = "PACK_HASH_DRIFT"
